site_name: OpenStackLDV
nav:
- 1. Inicio: 'README.md'
- 2. ¿Qué es un IaaS?: '02-IaaS/IaaS.md'   
- 3. OpenStack: '03-OpenStack/OpenStack.md'

- About:
    - 'Licencia': 'licencia.md'


##theme: 'windmill'
##theme: 'cinder'
## theme: 'rtd-dropdown'
theme:
  name: 'material'
  language: 'es'

markdown_extensions:
  - admonition
  - codehilite