site_name: OpenStackLDV
nav:
- 1. Inicio: 'README.md'
- 2. Cloud computing y computación distribuida: 02-Cloud/Cloud.md
- 3. ¿Qué es un IaaS?: '03-IaaS/IaaS.md'   
- 4. OpenStack: '04-OpenStack/OpenStack.md'
- 5. Servicios ofrecidos por OpenStackLDV: '05-Servicios/Servicios.md'
- 6. Recursos de OpenStackLDV: '06-Recursos/Recursos.md'
- 7. Acceso a panel web (Horizon) de OpenStackLDV: '07-Acceso/Acceso.md'
- 8. Primeros pasos en OpenStackLDV: '08-PrimerosPasos/PrimerosPasos.md'
- 9. Conceptos: '09-Conceptos/Conceptos.md'
- 10. Prácticas: 
  - 10.1. Iniciales (Horizon):
    - P01-Imágenes públicas: '10-Prácticas/01-Iniciales/P01-ImágenesPúblicas/P01-ImágenesPúblicas.md'
    - P02-Redes y routers: '10-Prácticas/01-Iniciales/P02-RedesRouters/P02-RedesRouters.md'
    - P03-Crear instancias: '10-Prácticas/01-Iniciales/P03-Instancias/P03-Instancias.md'
    - P04-IPs Flotantes y Grupos de Seguridad: '10-Prácticas/01-Iniciales/P04-IPsFlotantesGruposSeguridad/P04-IPsFlotantesGruposSeguridad.md'
    - P05-Claves SSH: '10-Prácticas/01-Iniciales/P05-ClavesSSH/P05-ClavesSSH.md'
    - P06-Snapshots de instancias: '10-Prácticas/01-Iniciales/P06-SnapshotsDeInstancias/P06-SnapshotsDeInstancias.md'
    - P07-Volúmenes: '10-Prácticas/01-Iniciales/P07-Volúmenes/P07-Volúmenes.md'
    - P08-Borrado de componentes: '10-Prácticas/01-Iniciales/P08-Borrado/P08-Borrado.md'
- About:
    - 'Licencia': 'licencia.md'


##theme: 'windmill'
##theme: 'cinder'
## theme: 'rtd-dropdown'
theme:
  name: 'material'
  language: 'es'

markdown_extensions:
  - admonition
  - codehilite
