site_name: OpenStackLDV
nav:
- 1. Inicio: 'README.md'
- 2. Cloud computing y computación distribuida: 02-Cloud/Cloud.md
- 3. ¿Qué es un IaaS?: '03-IaaS/IaaS.md'   
- 4. OpenStack: '04-OpenStack/OpenStack.md'
- 5. Servicios ofrecidos por OpenStackLDV: '05-Servicios/Servicios.md'
- 6. Recursos de OpenStackLDV: '06-Recursos/Recursos.md'
- 7. Acceso a panel web (Horizon) de OpenStackLDV: '07-Acceso/Acceso.md'
- 8. Primeros pasos en OpenStackLDV: '08-PrimerosPasos/PrimerosPasos.md'
- 9. Conceptos: '09-Conceptos/Conceptos.md'




- About:
    - 'Licencia': 'licencia.md'


##theme: 'windmill'
##theme: 'cinder'
## theme: 'rtd-dropdown'
theme:
  name: 'material'
  language: 'es'

markdown_extensions:
  - admonition
  - codehilite
