site_name: OpenStackLDV
nav:
- 1. Inicio: 'README.md'
- 2. Cloud computing y computación distribuida: 02-Cloud/Cloud.md
- 3. ¿Qué es un IaaS?: '03-IaaS/IaaS.md'   
- 4. OpenStack: '04-OpenStack/OpenStack.md'
- 5. Servicios ofrecidos por OpenStackLDV: '05-Servicios/Servicios.md'
- 6. Recursos de OpenStackLDV: '06-Recursos/Recursos.md'
- 7. Acceso a panel web (Horizon) de OpenStackLDV: '07-Acceso/Acceso.md'
- 8. Primeros pasos en OpenStackLDV: '08-PrimerosPasos/PrimerosPasos.md'
- 9. Conceptos: '09-Conceptos/Conceptos.md'
- 10. Actividades: 
  - 10.1. Horizon:
    - A01-Imágenes públicas: '10-Actividades/Horizon/ImágenesPúblicas/ImágenesPúblicas.md'
    - A02-Redes y routers: '10-Actividades/Horizon/RedesRouters/RedesRouters.md'
    - A03-Crear instancias: '10-Actividades/Horizon/Instancias/Instancias.md'
    - A04-IPs Flotantes y Grupos de Seguridad: '10-Actividades/Horizon/IPsFlotantesGruposSeguridad/IPsFlotantesGruposSeguridad.md'
    - A05-Claves SSH: '10-Actividades/Horizon/ClavesSSH/ClavesSSH.md'
    - A06-Acciones básicas con instancias: '10-Actividades/Horizon/AccionesBásicas/AccionesBásicas.md'
    - A07-Snapshots de instancias: '10-Actividades/Horizon/SnapshotsDeInstancias/SnapshotsDeInstancias.md'
    - A08-Redimensión, reconstrución y archivado de instancias: '10-Actividades/Horizon/RedimensiónReconstruciónArchivado/RedimensiónReconstruciónArchivado.md'
    - A09-Volúmenes: '10-Actividades/Horizon/Volúmenes/Volúmenes.md'
    - A10-Borrado de componentes: '10-Actividades/Horizon/Borrado/Borrado.md'
    - A11-Servidor Web: '10-Actividades/Horizon/ServidorWeb/ServidorWeb.md'
    - A12-Cloud Init: '10-Actividades/Horizon/CloudInit/CloudInit.md'
  - 10.2. OSC (Openstack Client):
    - A00-Instalación y configuración inicial: '10-Actividades/OSC/Instalacion-OSC/Instalacion-OSC.md'
    - A01-Imágenes públicas-OSC: '10-Actividades/OSC/ImágenesPúblicas-OSC/ImágenesPúblicas-OSC.md'
    - A02-Redes y routers-OSC: '10-Actividades/OSC/RedesRouters-OSC/RedesRouters-OSC.md'
    - A03-Crear instancias-OSC: '10-Actividades/OSC/Instancias-OSC/Instancias-OSC.md'
    - A04-IPs Flotantes y Grupos de Seguridad-OSC: '10-Actividades/OSC/IPsFlotantesGruposSeguridad-OSC/IPsFlotantesGruposSeguridad-OSC.md'
    - A05-Claves SSH-OSC: '10-Actividades/OSC/ClavesSSH-OSC/ClavesSSH-OSC.md'
    - A06-Acciones básicas con instancias-OSC: '10-Actividades/OSC/AccionesBásicas-OSC/AccionesBásicas-OSC.md'
    - A07-Snapshots de instancias-OSC: '10-Actividades/OSC/SnapshotsDeInstancias-OSC/SnapshotsDeInstancias-OSC.md'
    - A08-Redimensión, reconstrución y archivado de instancias-OSC: '10-Actividades/OSC/RedimensiónReconstruciónArchivado-OSC/RedimensiónReconstruciónArchivado-OSC.md'
    - A09-Volúmenes-OSC: '10-Actividades/OSC/Volúmenes-OSC/Volúmenes-OSC.md'
    - A10-Borrado de componentes-OSC: '10-Actividades/OSC/Borrado-OSC/Borrado-OSC.md'
    - A11-Servidor Web-OSC: '10-Actividades/OSC/ServidorWeb-OSC/ServidorWeb-OSC.md'
    - A12-Cloud Init-OSC: '10-Actividades/OSC/CloudInit-OSC/CloudInit-OSC.md'

- About:
    - 'Licencia': 'licencia.md'


##theme: 'windmill'
##theme: 'cinder'
## theme: 'rtd-dropdown'
theme:
  name: 'material'
  language: 'es'

markdown_extensions:
  - admonition
  - codehilite
  - extra
  - attr_list: ~
  - codehilite:
      guess_lang: false
      linenums: false
  - def_list: ~
  - footnotes: ~
  - md_in_html: ~
  - tables: ~
  - toc:
      permalink: true
